packages:
  - "apps/*"
  - "packages/*"

enableGlobalVirtualStore: false

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - arm64
    - x64
  libc:
    - glibc
    - musl

trustPolicy: no-downgrade

trustPolicyExclude:
  - "semver@6.3.1"

overrides:
  "@webext-core/isolated-element": "1.1.4"
  "ip-address": "10.3.1"
  "node-notifier>uuid": "11.1.1"
  "web-ext-run>tmp": "0.2.7"
  "fx-runner>shell-quote": "1.8.4"

allowBuilds:
  esbuild: false
  sharp: true
  spawn-sync: false
