import { usePreferences } from "./preferences";

const messages = {
  app: ["Laboratoire de capture", "Laboratorio de captura", "Capture laboratory"],
  lab: ["LE LABORATOIRE", "EL LABORATORIO", "THE LABORATORY"],
  subtitle: ["Explorer. Capturer. Vérifier.", "Explorar. Capturar. Verificar.", "Explore. Capture. Verify."],
  intro: ["Deux fournisseurs, une même exigence : chaque annonce compte.", "Dos proveedores, una misma exigencia: cada anuncio cuenta.", "Two providers, one standard: every listing counts."],
  capture: ["Nouvelle capture", "Nueva captura", "New capture"],
  history: ["Captures", "Capturas", "Captures"],
  compare: ["Évaluation", "Evaluación", "Evaluation"],
  independent: ["Deux parcours indépendants", "Dos caminos independientes", "Two independent paths"],
  independentHelp: ["Chaque capture utilise un seul fournisseur. La référence de l’extension sert uniquement à vérifier les résultats.", "Cada captura usa un solo proveedor. La referencia de la extensión sirve únicamente para verificar resultados.", "Each capture uses one provider. Extension references are only used to verify results."],
  source: ["Source", "Fuente", "Source"],
  provider: ["Fournisseur de capture", "Proveedor de captura", "Capture provider"],
  xaiDescription: ["Grok et recherche web xAI", "Grok y búsqueda web xAI", "Grok and xAI web search"],
  firecrawlDescription: ["Agent et extraction Firecrawl", "Agente y extracción Firecrawl", "Firecrawl Agent and extraction"],
  search: ["Recherche complète", "Búsqueda completa", "Complete search"],
  urls: ["Annonces connues", "Anuncios conocidos", "Known listings"],
  searchHelp: ["Toutes les pages et tous les détails. Aucun plafond d’annonces.", "Todas las páginas y todos los detalles. Sin un máximo de anuncios.", "Every page and every detail. No listing cap."],
  urlHelp: ["Une URL par ligne. Les doublons seront regroupés.", "Una URL por línea. Los duplicados se agruparán.", "One URL per line. Duplicates will be grouped."],
  name: ["Nom de la capture", "Nombre de la captura", "Capture name"],
  namePlaceholder: ["Maisons autour de Quimper", "Casas cerca de Quimper", "Houses around Quimper"],
  nativeUrl: ["URL de recherche native", "URL de búsqueda nativa", "Native search URL"],
  nativeUrlHelp: ["Facultatif : copiez la recherche Leboncoin pour conserver ses critères exacts.", "Opcional: copiá la búsqueda de Leboncoin para conservar sus criterios exactos.", "Optional: paste the Leboncoin search to preserve its exact criteria."],
  location: ["Localisation", "Ubicación", "Location"],
  query: ["Mots-clés", "Palabras clave", "Keywords"],
  category: ["Catégorie", "Categoría", "Category"],
  sale: ["Ventes immobilières", "Venta de inmuebles", "Property sales"],
  rent: ["Locations", "Alquileres", "Rentals"],
  propertyType: ["Type de bien", "Tipo de inmueble", "Property type"],
  any: ["Tous", "Todos", "All"],
  house: ["Maison", "Casa", "House"],
  apartment: ["Appartement", "Departamento", "Apartment"],
  land: ["Terrain", "Terreno", "Land"],
  seller: ["Vendeur", "Vendedor", "Seller"],
  privateSeller: ["Particulier", "Particular", "Private"],
  professional: ["Professionnel", "Profesional", "Professional"],
  minPrice: ["Prix minimum (€)", "Precio mínimo (€)", "Minimum price (€)"],
  maxPrice: ["Prix maximum (€)", "Precio máximo (€)", "Maximum price (€)"],
  minSurface: ["Surface minimum (m²)", "Superficie mínima (m²)", "Minimum area (m²)"],
  maxSurface: ["Surface maximum (m²)", "Superficie máxima (m²)", "Maximum area (m²)"],
  rooms: ["Pièces minimum", "Ambientes mínimos", "Minimum rooms"],
  bedrooms: ["Chambres minimum", "Dormitorios mínimos", "Minimum bedrooms"],
  order: ["Ordre", "Orden", "Order"],
  newest: ["Plus récentes", "Más recientes", "Newest"],
  priceAsc: ["Prix croissant", "Menor precio", "Lowest price"],
  priceDesc: ["Prix décroissant", "Mayor precio", "Highest price"],
  start: ["Lancer la capture", "Iniciar captura", "Start capture"],
  starting: ["Création…", "Creando…", "Creating…"],
  configurationNeeded: ["Configurez ce fournisseur dans le backend pour lancer une capture.", "Configurá este proveedor en el backend para iniciar una captura.", "Configure this provider in the backend to start a capture."],
  unknownConsumption: ["Consommation inconnue : rapprochement nécessaire.", "Consumo desconocido: se necesita reconciliarlo.", "Unknown usage: reconciliation is required."],
  budget: ["Budget de cette POC", "Presupuesto de esta POC", "POC budget"],
  spent: ["consommé", "consumido", "used"],
  credits: ["crédits", "créditos", "credits"],
  loading: ["Chargement…", "Cargando…", "Loading…"],
  refresh: ["Actualiser", "Actualizar", "Refresh"],
  noRuns: ["La première capture commence ici", "La primera captura empieza acá", "Your first capture starts here"],
  noRunsHelp: ["Choisissez une source et un fournisseur. Les résultats resteront disponibles après la fermeture de cette fenêtre.", "Elegí una fuente y un proveedor. Los resultados seguirán disponibles al cerrar esta ventana.", "Choose a source and provider. Results remain available when you close this window."],
  noResults: ["Aucune annonce reçue pour le moment", "Todavía no se recibieron anuncios", "No listings received yet"],
  noResultsHelp: ["Les annonces apparaîtront ici au fil de la capture.", "Los anuncios aparecerán acá durante la captura.", "Listings will appear here as the capture progresses."],
  results: ["Résultats", "Resultados", "Results"],
  pages: ["Étapes de recherche", "Pasos de búsqueda", "Discovery steps"],
  discovered: ["Annonces découvertes", "Anuncios descubiertos", "Discovered listings"],
  details: ["Fiches extraites", "Fichas extraídas", "Extracted details"],
  pending: ["Tâches en attente", "Tareas pendientes", "Queued work"],
  coverage: ["Couverture", "Cobertura", "Coverage"],
  coverageHelp: ["Une capture terminée ne prouve pas sa couverture. Comparez ses identifiants à une référence complète.", "Una captura terminada no demuestra su cobertura. Compará sus identidades con una referencia completa.", "A finished capture does not prove coverage. Compare its listing identities with a complete reference."],
  stop: ["Arrêter", "Detener", "Stop"],
  resume: ["Reprendre", "Reanudar", "Resume"],
  export: ["Exporter", "Exportar", "Export"],
  exportJson: ["Exporter tous les résultats · JSON", "Exportar todos los resultados · JSON", "Export all results · JSON"],
  cards: ["Cartes", "Tarjetas", "Cards"],
  table: ["Tableau", "Tabla", "Table"],
  previous: ["Précédent", "Anterior", "Previous"],
  next: ["Suivant", "Siguiente", "Next"],
  title: ["Annonce", "Anuncio", "Listing"],
  price: ["Prix", "Precio", "Price"],
  surface: ["Surface", "Superficie", "Area"],
  observed: ["Observé le", "Observado el", "Observed at"],
  unknown: ["Non renseigné", "Sin datos", "Unknown"],
  openListing: ["Voir l’annonce", "Ver anuncio", "Open listing"],
  missing: ["Non récupéré", "No recuperado", "Not retrieved"],
  absent: ["Absent de la source", "Ausente en la fuente", "Absent from source"],
  evidence: ["Éléments de preuve", "Evidencias", "Evidence"],
  description: ["Description", "Descripción", "Description"],
  images: ["Images", "Imágenes", "Images"],
  close: ["Fermer", "Cerrar", "Close"],
  selectRun: ["Sélectionnez une capture", "Seleccioná una captura", "Select a capture"],
  recent: ["Historique des captures", "Historial de capturas", "Capture history"],
  comparisonIntro: ["100 % des identifiants. Chaque champ vérifié.", "100 % de las identidades. Cada campo verificado.", "100% of identities. Every field verified."],
  comparisonHelp: ["Importez une référence indépendante, puis confrontez les captures des deux fournisseurs à cette même référence.", "Importá una referencia independiente y compará las capturas de ambos proveedores con esa misma referencia.", "Import an independent reference, then compare both providers against that same reference."],
  importReference: ["Importer une référence", "Importar referencia", "Import reference"],
  reference: ["Référence de l’extension", "Referencia de la extensión", "Extension reference"],
  referenceName: ["Nom de la référence", "Nombre de la referencia", "Reference name"],
  referenceComplete: ["Toutes les pages de la recherche ont été vérifiées", "Se verificaron todas las páginas de la búsqueda", "All search pages have been verified"],
  referenceReconciled: ["Les changements d’annonces ont été rapprochés", "Se reconciliaron los cambios de anuncios", "Listing changes have been reconciled"],
  referenceHelp: ["Chargez un export JSON de l’extension ou un cas de référence du laboratoire. Ne déclarez complète qu’une recherche entièrement observée.", "Cargá una exportación JSON de la extensión o un caso de referencia del laboratorio. Marcá completa únicamente una búsqueda observada en su totalidad.", "Load an extension JSON export or a laboratory reference case. Only mark a search complete when fully observed."],
  import: ["Importer", "Importar", "Import"],
  evaluate: ["Comparer les captures", "Comparar capturas", "Compare captures"],
  noReference: ["Ajoutez une référence pour vérifier la couverture.", "Agregá una referencia para verificar la cobertura.", "Add a reference to verify coverage."],
  expected: ["Attendus", "Esperados", "Expected"],
  matched: ["Correspondances", "Coincidencias", "Matched"],
  missingIds: ["Identifiants manquants", "Identidades faltantes", "Missing identities"],
  extraIds: ["Identifiants supplémentaires", "Identidades adicionales", "Extra identities"],
  differences: ["Différences à examiner", "Diferencias para revisar", "Differences to review"],
  report: ["Rapport", "Informe", "Report"],
  diagnosticHelp: ["Les clés API et les budgets sont configurés dans collector-api. Aucune clé n’est conservée par cette application.", "Las claves API y los presupuestos se configuran en collector-api. Esta aplicación no conserva ninguna clave.", "API keys and budgets are configured in collector-api. This application stores no API keys."],
  api: ["API du laboratoire", "API del laboratorio", "Laboratory API"],
  configured: ["Configuré", "Configurado", "Configured"],
  unconfigured: ["Non configuré", "Sin configurar", "Not configured"],
  invalidJson: ["Le fichier ne contient pas un JSON valide.", "El archivo no contiene JSON válido.", "The file does not contain valid JSON."],
  queued: ["En attente", "En cola", "Queued"],
  running: ["En cours", "En curso", "Running"],
  completed: ["Exécution terminée", "Ejecución terminada", "Execution finished"],
  paused: ["En pause", "Pausada", "Paused"],
  cancelled: ["Arrêtée", "Detenida", "Stopped"],
  failed: ["Échec", "Falló", "Failed"],
  interrupted: ["Interrompue", "Interrumpida", "Interrupted"],
  budget_exhausted: ["Budget consommé", "Presupuesto consumido", "Budget exhausted"],
  uncertain: ["État incertain", "Estado incierto", "Uncertain state"],
  unverified: ["Non vérifiée", "Sin verificar", "Unverified"],
  incomplete: ["Capture incomplète", "Captura incompleta", "Incomplete capture"],
  complete: ["Couverture complète vérifiée", "Cobertura completa verificada", "Complete coverage verified"],
  inconclusive: ["Non concluant", "Inconcluso", "Inconclusive"],
  blocked: ["Limitation technique", "Limitación técnica", "Technical limitation"],
  discovery: ["Découverte des annonces", "Descubriendo anuncios", "Discovering listings"],
  detail: ["Extraction des détails", "Extrayendo detalles", "Extracting details"],
  preparation: ["Préparation", "Preparación", "Preparing"],
  done: ["Traitement terminé", "Procesamiento terminado", "Processing finished"],
  notes: ["Notes de vérification", "Notas de verificación", "Verification notes"],
  saveReview: ["Enregistrer la vérification", "Guardar revisión", "Save review"],
  reviewHelp: ["Documentez les changements du site et les preuves examinées avant de rapprocher la référence.", "Documentá los cambios del sitio y la evidencia revisada antes de reconciliar la referencia.", "Document site changes and reviewed evidence before reconciling the reference."],
  reportHistory: ["Rapports enregistrés", "Informes guardados", "Saved reports"],
  reportHistoryHelp: ["Rouvrez une comparaison conservée, sans relancer la capture ni son évaluation.", "Reabrí una comparación guardada, sin volver a capturar ni evaluarla.", "Reopen a saved comparison without rerunning its capture or evaluation."],
  noReports: ["Aucun rapport enregistré pour le moment.", "Todavía no hay informes guardados.", "No saved reports yet."],
  openReport: ["Ouvrir le rapport", "Abrir informe", "Open report"],
  strategy: ["Stratégie de capture", "Estrategia de captura", "Capture strategy"],
  strategyPage: ["Agent : une page par tâche", "Agent: página por trabajo", "Agent: one page per job"],
  strategyNative: ["Agent : navigation native", "Agent: navegación nativa", "Agent: native navigation"],
  strategyExpanded: ["Agent + détails dépliés", "Agent + detalles desplegados", "Agent + expanded details"],
  strategyXai: ["Recherche web xAI", "Búsqueda web xAI", "xAI web search"],
  strategyHelp: ["La stratégie choisie est conservée pour toute cette capture et ses reprises.", "La estrategia elegida se conserva durante toda esta captura y sus reanudaciones.", "The selected strategy is kept throughout this capture and its resumptions."],
  strategyUnavailable: ["Cette stratégie n’est plus disponible. Sélectionnez une autre stratégie.", "Esta estrategia ya no está disponible. Seleccioná otra estrategia.", "This strategy is no longer available. Select another strategy."],
  estimatedCost: ["Estimation", "Estimado", "Estimated"],
  confirmedCost: ["Confirmé", "Confirmado", "Confirmed"],
  requiredFields: ["Champs à vérifier", "Campos a verificar", "Fields to verify"],
  landSurface: ["Surface du terrain", "Superficie del terreno", "Land area"],
  roomsCount: ["Pièces", "Ambientes", "Rooms"],
  bedroomsCount: ["Chambres", "Dormitorios", "Bedrooms"],
  sellerName: ["Nom du vendeur", "Nombre del vendedor", "Seller name"],
  postedAt: ["Publication", "Publicación", "Posted at"],
  features: ["Caractéristiques", "Características", "Features"],
  coverageTarget: ["Objectif de couverture", "Objetivo de cobertura", "Coverage target"],
  balances: ["Actualiser les soldes", "Actualizar saldos", "Refresh balances"],
  availableBalance: ["Solde du fournisseur", "Saldo del proveedor", "Provider balance"],
  expires: ["Expiration des crédits", "Vencimiento de los créditos", "Credit expiry"],
  reconcile: ["Rapprocher la consommation", "Reconciliar consumo", "Reconcile usage"],
  reconcileHelp: ["Utilisez le coût constaté dans la console du fournisseur. Cette action met à jour le registre du laboratoire.", "Usá el costo observado en la consola del proveedor. Esta acción actualiza el registro del laboratorio.", "Use the cost observed in the provider console. This updates the laboratory ledger."],
  amount: ["Coût confirmé", "Costo confirmado", "Confirmed cost"],
  online: ["Connectée", "Conectada", "Connected"],
  offline: ["Indisponible", "No disponible", "Unavailable"],
  validation: ["Vérifiez les champs : URL HTTPS, critères de recherche et bornes minimum/maximum.", "Revisá los campos: URL HTTPS, criterios de búsqueda y límites mínimo/máximo.", "Check the fields: HTTPS URL, search criteria, and minimum/maximum ranges."],
  simulation: ["Données simulées · aucun résultat réel", "Datos simulados · sin resultados reales", "Simulated data · no live results"],
  shared: ["Colocations", "Alquiler compartido", "Shared rentals"],
  commercial: ["Bureaux et commerces", "Oficinas y comercios", "Commercial property"],
  new: ["Immobilier neuf", "Inmuebles nuevos", "New property"],
  parking: ["Parking", "Estacionamiento", "Parking"],
  other: ["Autre", "Otro", "Other"],
  relevance: ["Pertinence", "Relevancia", "Relevance"],
  maxRooms: ["Pièces maximum", "Ambientes máximos", "Maximum rooms"],
  maxBedrooms: ["Chambres maximum", "Dormitorios máximos", "Maximum bedrooms"],
  activity: ["Journal de capture", "Actividad de captura", "Capture activity"],
  inspection: ["Vérification détaillée", "Verificación detallada", "Detailed verification"],
  expectedValue: ["Valeur de référence", "Valor de referencia", "Reference value"],
  actualValue: ["Valeur capturée", "Valor capturado", "Captured value"],
  confirmed_match: ["Correspondance confirmée", "Coincidencia confirmada", "Confirmed match"],
  confirmed_error: ["Erreur confirmée", "Error confirmado", "Confirmed error"],
  source_changed: ["Source modifiée", "Fuente modificada", "Source changed"],
  source_absent: ["Champ absent de la source", "Campo ausente en la fuente", "Field absent from source"],
  evidenceUrl: ["URL de la preuve", "URL de la evidencia", "Evidence URL"],
  resolution: ["Conclusion de la vérification", "Conclusión de la revisión", "Review resolution"],
  saved: ["Enregistré", "Guardado", "Saved"],
  missing_listing: ["Annonce manquante", "Anuncio faltante", "Missing listing"],
  extra_listing: ["Annonce supplémentaire", "Anuncio adicional", "Extra listing"],
  missing_field: ["Champ manquant", "Campo faltante", "Missing field"],
  different_value: ["Valeur différente", "Valor distinto", "Different value"],
  pending_detail: ["Détail en attente", "Detalle pendiente", "Pending detail"],
  missing_evidence: ["Preuve manquante", "Evidencia faltante", "Missing evidence"],
  recall: ["Identifiants retrouvés", "Identidades recuperadas", "Identity recall"],
  detailCoverage: ["Détails traités", "Detalles procesados", "Detail coverage"],
  fieldCompleteness: ["Champs récupérés", "Campos recuperados", "Field completeness"],
  fieldAccuracy: ["Exactitude des champs", "Exactitud de campos", "Field accuracy"],
  imageCoverage: ["Couverture des images", "Cobertura de imágenes", "Image coverage"],
  noDifferences: ["Aucune différence détectée", "No se detectaron diferencias", "No differences detected"],
  searchPages: ["Pages de référence (une URL par ligne)", "Páginas de referencia (una URL por línea)", "Reference pages (one URL per line)"],
  capturedAt: ["Date de la capture de référence", "Fecha de captura de referencia", "Reference capture date"],
  registered: ["Référence importée", "Referencia importada", "Reference imported"],
  status: ["État", "Estado", "Status"],
} as const;

export type CopyKey = keyof typeof messages;
export function getCopy(locale: "fr" | "es" | "en", key: CopyKey) { return messages[key][locale === "fr" ? 0 : locale === "es" ? 1 : 2]; }
export function useCopy() { const locale = usePreferences((state) => state.locale); return (key: CopyKey) => getCopy(locale, key); }
export function isCopyKey(value: string): value is CopyKey { return value in messages; }
