import type { PropertyListing, ScoringMetric, ScoringRecipe } from "../types";

export const providers = ["SeLoger", "Bien'ici", "Leboncoin", "Ouest-France"] as const;

export const properties: PropertyListing[] = [
  {
    id: "p1",
    title: "Maison en pierre",
    locality: "Cancale",
    address: "12 rue de la Visitation, 35260 Cancale",
    price: 264000,
    surfaceM2: 96,
    rooms: 4,
    provider: "SeLoger",
    coordinates: { lat: 48.679, lng: -1.852 },
    dpe: "D",
    scores: { overall: 8.2, coast: 9.4, quiet: 6.2, value: 7.1, family: 8.0, transit: 7.4, dpe: 6.3, flood: 8.8 },
    postedDaysAgo: 3,
    diagnostics: {
      irisMedianPrice: 2860,
      comparableSales: 8,
      noiseDbNight: 57,
      coastalDistanceKm: 0.8,
      transitMinutes: 6,
    },
  },
  {
    id: "p2",
    title: "Longere renovee",
    locality: "Saint-Briac",
    address: "8 chemin du Bourg, 35800 Saint-Briac-sur-Mer",
    price: 318000,
    surfaceM2: 124,
    rooms: 5,
    provider: "Bien'ici",
    coordinates: { lat: 48.62, lng: -2.13 },
    dpe: "C",
    scores: { overall: 7.9, coast: 8.6, quiet: 8.2, value: 6.4, family: 6.8, transit: 5.2, dpe: 7.3, flood: 8.1 },
    postedDaysAgo: 12,
    diagnostics: {
      irisMedianPrice: 2730,
      comparableSales: 6,
      noiseDbNight: 38,
      coastalDistanceKm: 1.9,
      transitMinutes: 18,
    },
  },
  {
    id: "p3",
    title: "Appartement T3",
    locality: "Rennes centre",
    address: "Rue de Nantes, 35000 Rennes",
    price: 195000,
    surfaceM2: 64,
    rooms: 3,
    provider: "Leboncoin",
    coordinates: { lat: 48.107, lng: -1.679 },
    dpe: "C",
    scores: { overall: 6.9, coast: 3.0, quiet: 6.8, value: 7.3, family: 7.1, transit: 9.4, dpe: 7.5, flood: 7.0 },
    postedDaysAgo: 5,
    diagnostics: {
      irisMedianPrice: 3260,
      comparableSales: 21,
      noiseDbNight: 51,
      coastalDistanceKm: 65,
      transitMinutes: 2,
    },
  },
  {
    id: "p4",
    title: "Maison de bord de mer",
    locality: "Dinard",
    address: "Avenue George V, 35800 Dinard",
    price: 412000,
    surfaceM2: 110,
    rooms: 4,
    provider: "SeLoger",
    coordinates: { lat: 48.633, lng: -2.062 },
    dpe: "D",
    scores: { overall: 7.4, coast: 9.6, quiet: 6.5, value: 5.2, family: 7.0, transit: 6.1, dpe: 6.2, flood: 7.4 },
    postedDaysAgo: 21,
    diagnostics: {
      irisMedianPrice: 4080,
      comparableSales: 14,
      noiseDbNight: 54,
      coastalDistanceKm: 0.5,
      transitMinutes: 11,
    },
  },
  {
    id: "p5",
    title: "Maison familiale",
    locality: "Pleurtuit",
    address: "12 rue des Forges, 35730 Pleurtuit",
    price: 232000,
    surfaceM2: 88,
    rooms: 4,
    provider: "Bien'ici",
    coordinates: { lat: 48.572, lng: -2.05 },
    dpe: "C",
    scores: { overall: 7.6, coast: 6.4, quiet: 7.8, value: 7.4, family: 7.9, transit: 6.0, dpe: 7.1, flood: 8.4 },
    postedDaysAgo: 8,
    diagnostics: {
      irisMedianPrice: 2840,
      comparableSales: 10,
      noiseDbNight: 42,
      coastalDistanceKm: 7.8,
      transitMinutes: 15,
    },
  },
  {
    id: "p6",
    title: "Maison en pierre",
    locality: "Plouer-sur-Rance",
    address: "6 ruelle Verte, 22490 Plouer-sur-Rance",
    price: 178000,
    surfaceM2: 76,
    rooms: 3,
    provider: "Leboncoin",
    coordinates: { lat: 48.527, lng: -2.001 },
    dpe: "E",
    scores: { overall: 7.0, coast: 6.0, quiet: 7.8, value: 8.2, family: 6.2, transit: 4.8, dpe: 4.8, flood: 7.7 },
    postedDaysAgo: 2,
    diagnostics: {
      irisMedianPrice: 2650,
      comparableSales: 5,
      noiseDbNight: 41,
      coastalDistanceKm: 12,
      transitMinutes: 27,
    },
  },
  {
    id: "p7",
    title: "Maison intra-muros",
    locality: "Saint-Malo",
    address: "Rue Surcouf, 35400 Saint-Malo",
    price: 489000,
    surfaceM2: 132,
    rooms: 5,
    provider: "SeLoger",
    coordinates: { lat: 48.65, lng: -2.026 },
    dpe: "D",
    scores: { overall: 7.7, coast: 9.0, quiet: 5.4, value: 4.2, family: 7.4, transit: 7.2, dpe: 6.0, flood: 6.8 },
    postedDaysAgo: 17,
    diagnostics: {
      irisMedianPrice: 3960,
      comparableSales: 19,
      noiseDbNight: 59,
      coastalDistanceKm: 0.3,
      transitMinutes: 7,
    },
  },
  {
    id: "p8",
    title: "Maison de bourg",
    locality: "Pleslin-Trigavou",
    address: "Rue de l'Eglise, 22490 Pleslin-Trigavou",
    price: 209000,
    surfaceM2: 94,
    rooms: 4,
    provider: "Bien'ici",
    coordinates: { lat: 48.54, lng: -2.063 },
    dpe: "D",
    scores: { overall: 7.1, coast: 5.4, quiet: 7.6, value: 7.6, family: 6.6, transit: 5.5, dpe: 6.1, flood: 8.0 },
    postedDaysAgo: 6,
    diagnostics: {
      irisMedianPrice: 2480,
      comparableSales: 9,
      noiseDbNight: 44,
      coastalDistanceKm: 14,
      transitMinutes: 22,
    },
  },
  {
    id: "p9",
    title: "Maison contemporaine",
    locality: "Dinan",
    address: "Rue de la Ferronnerie, 22100 Dinan",
    price: 287000,
    surfaceM2: 102,
    rooms: 4,
    provider: "Ouest-France",
    coordinates: { lat: 48.456, lng: -2.045 },
    dpe: "B",
    scores: { overall: 7.5, coast: 4.8, quiet: 8.0, value: 7.0, family: 7.6, transit: 6.4, dpe: 8.8, flood: 8.6 },
    postedDaysAgo: 14,
    diagnostics: {
      irisMedianPrice: 2990,
      comparableSales: 13,
      noiseDbNight: 39,
      coastalDistanceKm: 23,
      transitMinutes: 10,
    },
  },
  {
    id: "p10",
    title: "Penty renove",
    locality: "Cancale",
    address: "Rue du Port, 35260 Cancale",
    price: 224000,
    surfaceM2: 72,
    rooms: 3,
    provider: "SeLoger",
    coordinates: { lat: 48.682, lng: -1.857 },
    dpe: "D",
    scores: { overall: 7.4, coast: 9.2, quiet: 7.1, value: 7.0, family: 6.0, transit: 6.8, dpe: 6.4, flood: 7.2 },
    postedDaysAgo: 1,
    diagnostics: {
      irisMedianPrice: 3330,
      comparableSales: 7,
      noiseDbNight: 46,
      coastalDistanceKm: 0.4,
      transitMinutes: 9,
    },
  },
  {
    id: "p11",
    title: "Maison",
    locality: "Cesson-Sevigne",
    address: "Rue de Paris, 35510 Cesson-Sevigne",
    price: 365000,
    surfaceM2: 118,
    rooms: 5,
    provider: "Bien'ici",
    coordinates: { lat: 48.124, lng: -1.601 },
    dpe: "C",
    scores: { overall: 7.2, coast: 3.4, quiet: 7.4, value: 6.6, family: 8.4, transit: 8.8, dpe: 7.2, flood: 8.9 },
    postedDaysAgo: 9,
    diagnostics: {
      irisMedianPrice: 3270,
      comparableSales: 16,
      noiseDbNight: 43,
      coastalDistanceKm: 61,
      transitMinutes: 5,
    },
  },
  {
    id: "p12",
    title: "Maison ancienne",
    locality: "Lamballe",
    address: "Rue Saint-Martin, 22400 Lamballe",
    price: 165000,
    surfaceM2: 88,
    rooms: 4,
    provider: "Leboncoin",
    coordinates: { lat: 48.467, lng: -2.515 },
    dpe: "E",
    scores: { overall: 6.4, coast: 5.2, quiet: 7.6, value: 8.4, family: 6.0, transit: 4.4, dpe: 4.7, flood: 7.9 },
    postedDaysAgo: 4,
    diagnostics: {
      irisMedianPrice: 2260,
      comparableSales: 11,
      noiseDbNight: 42,
      coastalDistanceKm: 19,
      transitMinutes: 29,
    },
  },
];

export const scorings: ScoringMetric[] = [
  {
    id: "coast",
    group: "Lieu",
    name: "Acces littoral",
    icon: "waves",
    short: "Distance, relief et temps d'acces reel vers la cote.",
    formula: "100 x exp(-d_cote / 8 km) - penalite_route",
    inputs: ["Polygones cotiers IGN", "Reseau routier OSM", "Denivele cumule"],
    sample: { good: "Cancale, 800 m de la plage", weak: "Rennes centre, 65 km" },
    tags: ["IGN", "OSM"],
    builtIn: true,
  },
  {
    id: "quiet",
    group: "Environnement",
    name: "Calme nuit",
    icon: "volume-x",
    short: "Niveau sonore median estime entre 22h et 6h.",
    formula: "55 - Lden_nuit, ramene sur 0-10",
    inputs: ["Cartes de bruit", "Axes routiers majeurs", "Voies ferrees"],
    sample: { good: "Saint-Briac, 38 dB", weak: "Abords D137, 67 dB" },
    tags: ["CEREMA", "DREAL"],
    builtIn: true,
  },
  {
    id: "value",
    group: "Marche",
    name: "Valeur IRIS",
    icon: "chart-no-axes-combined",
    short: "Ecart prix/m2 du bien contre transactions comparables.",
    formula: "z-score inverse du prix/m2 vs IRIS sur 12 mois",
    inputs: ["DVF", "IRIS INSEE", "Typologie comparable"],
    sample: { good: "-12 % vs IRIS, 8 ventes", weak: "+24 % vs IRIS" },
    tags: ["DVF", "INSEE"],
    builtIn: true,
  },
  {
    id: "family",
    group: "Vie quotidienne",
    name: "Vie de famille",
    icon: "school",
    short: "Ecoles, creches, parcs et securite de secteur.",
    formula: "0.4 x ecoles + 0.3 x creches + 0.2 x parcs + 0.1 x securite",
    inputs: ["Education nationale", "Parcs OSM", "Indicateurs communaux"],
    sample: { good: "Pleurtuit, ecole A + parc 300 m", weak: "ZI, pas d'ecole proche" },
    tags: ["EN", "OSM"],
    builtIn: true,
  },
  {
    id: "transit",
    group: "Mobilite",
    name: "TER et bus",
    icon: "train",
    short: "Temps de trajet et frequence vers Rennes / Saint-Malo.",
    formula: "10 x (1 - t_rennes / 90 min) avec correctif frequence",
    inputs: ["GTFS TER", "BreizhGo", "Marche OSRM"],
    sample: { good: "Dinan, TER 28 min", weak: "Plouer, bus rare" },
    tags: ["GTFS", "OSRM"],
    builtIn: true,
  },
  {
    id: "dpe",
    group: "Bien",
    name: "Energie DPE",
    icon: "battery-charging",
    short: "Etiquette DPE convertie en score avec correction age.",
    formula: "lookup(DPE) - 0.5 x (diagnostic > 5 ans)",
    inputs: ["DPE annonce", "ADEME open data", "Annee diagnostic"],
    sample: { good: "B, diagnostic 2024", weak: "F, diagnostic 2017" },
    tags: ["ADEME"],
    builtIn: true,
  },
  {
    id: "flood",
    group: "Risque",
    name: "Inondation",
    icon: "cloud-rain",
    short: "Probabilite d'etre en zone PPRI risquee.",
    formula: "10 x (1 - P_zonage) avec decote zone rouge",
    inputs: ["PPRI Georisques", "Altitude", "Distance cours d'eau"],
    sample: { good: "Hors zone, altitude +18 m", weak: "Zone bleue crue centennale" },
    tags: ["Georisques"],
    builtIn: true,
  },
  {
    id: "weekend",
    group: "Composite",
    name: "Weekend retreat",
    icon: "sparkles",
    short: "Score composite pour residence secondaire en Bretagne nord.",
    formula: "0.35 x cote + 0.25 x calme + 0.20 x valeur + 0.10 x TER + 0.10 x DPE",
    inputs: ["Acces littoral", "Calme", "Valeur", "Mobilite", "DPE"],
    sample: { good: "Cancale, 8.2 global", weak: "Lamballe, 6.4 global" },
    tags: ["Custom", "Composite"],
    builtIn: false,
  },
];

export const recipes: ScoringRecipe[] = [
  {
    id: "weekend",
    name: "Weekend retreat",
    description: "Residence secondaire, acces mer rapide, calme la nuit, prix defendable.",
    status: "draft",
    weights: { coast: 35, quiet: 25, value: 20, transit: 10, dpe: 10, family: 0, flood: 0 },
    filters: [
      { id: "f1", field: "price", operator: "lte", value: "480000" },
      { id: "f2", field: "type", operator: "eq", value: "Maison" },
      { id: "f3", field: "dpe", operator: "lte", value: "D" },
    ],
  },
  {
    id: "family",
    name: "Maison famille",
    description: "Vie quotidienne, ecoles, calme et mobilite avant proximite littorale.",
    status: "saved",
    weights: { coast: 5, quiet: 20, value: 15, transit: 15, dpe: 10, family: 35, flood: 0 },
    filters: [
      { id: "f4", field: "surface", operator: "gte", value: "85" },
      { id: "f5", field: "rooms", operator: "gte", value: "4" },
    ],
  },
  {
    id: "invest",
    name: "Investissement locatif",
    description: "Rendement potentiel, transport et sous-valorisation locale.",
    status: "saved",
    weights: { coast: 10, quiet: 5, value: 40, transit: 25, dpe: 10, family: 5, flood: 5 },
    filters: [
      { id: "f6", field: "price", operator: "lte", value: "320000" },
      { id: "f7", field: "transit", operator: "gte", value: "6" },
    ],
  },
];
